# Generated by Django 5.0.2 on 2024-03-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_projectmanagement_delete_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='final_mark',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='personal_mark',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
