# Generated by Django 5.0.2 on 2024-03-03 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_project_final_mark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='projectmanagement',
            name='academic_id',
        ),
        migrations.RemoveField(
            model_name='projectmanagement',
            name='project_id',
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmanagement',
            name='academic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmanagement',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management', to='app.project'),
        ),
    ]
